#name: Notify
#
#on:
#  push:
#    paths-ignore:
#      - 'docs/**'
#      - '*.md'
#      - '.gitignore'
#      - 'docker/**'
#      - 'webassembly.yml'
#  pull_request:
#    paths-ignore:
#      - 'docs/**'
#      - '*.md'
#      - '.gitignore'
#      - 'docker/**'
#      - 'webassembly.yml'
#
#jobs:
#
#  build:
#    if: "!contains(github.event.head_commit.message, 'skip ci')"
#    name: Ubuntu 18.04
#    runs-on: ubuntu-latest
#
#    env:
#      GIT: "https://github.com"
#      CMAKE_VER: "3.18.4"
#      MANUAL_CACHING: "6"
#      AUTO_CACHING: "1"
#
#    steps:
#
#      - name: Discord notification
#        env:
#          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
#        uses: Ilshidur/action-discord@master
#        with:
#          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'